# Generated by Django 5.0.4 on 2024-05-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SHNKGroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(max_length=15)),
                ('group_name_uz', models.CharField(max_length=255)),
                ('group_name_ru', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnksystemsmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK groups',
                'db_table': 'shnk_groups',
            },
        ),
    ]
