# Generated by Django 5.0.4 on 2024-05-09 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0003_shnktypesmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SHNKDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shnk_name_uz', models.CharField(max_length=255, unique=True)),
                ('shnk_name_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('shnk_code', models.CharField(max_length=3)),
                ('shnk_file_uz', models.FileField(blank=True, null=True, upload_to='shnk')),
                ('shnk_file_ru', models.FileField(blank=True, null=True, upload_to='shnk')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shnk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnkgroupsmodel')),
                ('shnk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnktypesmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK documents',
                'db_table': 'shnk_documents',
            },
        ),
    ]
