# Generated by Django 5.0.4 on 2024-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0004_shnkdocumentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shnkdocumentsmodel',
            name='shnk_code',
            field=models.CharField(max_length=10),
        ),
    ]
