# Generated by Django 5.0.4 on 2024-05-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0005_alter_shnkdocumentsmodel_shnk_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SHNKDocPartsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_title_uz', models.CharField(max_length=255, unique=True)),
                ('part_title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('part_number', models.IntegerField()),
                ('part_text_uz', models.CharField(max_length=255, null=True)),
                ('part_text_ru', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnkdocumentsmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK doc_parts',
                'db_table': 'shnk_doc_parts',
            },
        ),
    ]
