# Generated by Django 5.0.4 on 2024-05-11 14:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0007_shnkdocplansmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shnkdocpartsmodel',
            name='has_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shnkdocplansmodel',
            name='has_subplan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shnkdocpartsmodel',
            name='part_text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='shnkdocpartsmodel',
            name='part_text_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='shnkdocplansmodel',
            name='plan_text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='shnkdocplansmodel',
            name='plan_text_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
